spring:
  datasource:
    url: jdbc:h2:file:./database/sistem_blog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console: true
    path: /h2-console
#propiedades hibernate
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
#propiedades jwt
app:
  jwt-secret: 123143524SWE213231U123131231O1321123JJ21123
  jwt-expiration-milliseconds: 604800000